### PR TITLE
refactor: clean up type exports and fix linting

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Review by cabreraalex — CHANGES_REQUESTED** [review]
Do we need the specific VegaSpec and VegaLiteSpec since they are wrapped by VisualizationSpec?

nit: single vs. double quotes

**Comment by domoritz** [comment]
It can be useful to have the specific types but one can also get the from Vega and Vega-Lite. I'm happy to remove them for now.

**Comment by cabreraalex** [comment]
I'm indifferent, probably fine since they don't add size?

**Comment by domoritz** [comment]
They don't add anything at runtime. It just means we cannot remove the exported types in the future but I think that's fine.

Something is wrong about our eslint setup. It should have caught the formatting issue.

**Comment by domoritz** [comment]
Fixed the linting. Please have another look.

**Comment by cabreraalex** [comment]
lgtm

**Review by cabreraalex — APPROVED** [review]

**Pull request merged**
